[versions]
spotless                    = "6.13.0"
diktat                      = "1.2.4.2"

[libraries]

[bundles]

[plugins]
spotless                    = { id = "com.diffplug.spotless", version.ref = "spotless" }